### ISSUE TITLE
bug on adopt-openj9@1.8.0-242 with CQEngine

### ISSUE THREAD

**Issue by max402** [adorsys/keystore-management#7]
`Caused by: java.lang.IllegalStateException: Could not resolve sufficient generic type information from the given function of type: de.adorsys.keymanagement.core.view.EntryViewImpl$$Lambda$1355/000000002649A4F0, resolved: [class net.jodah.typetools.TypeResolver$Unknown, class net.jodah.typetools.TypeResolver$Unknown]. If the function you supplied was created from a lambda expression, then it's likely that the host JVM does not allow the generic type information to be read from lambda expressions. Alternatively, if you supplied a class-based implementation of the function, then you must ensure that you specified the generic types of the function when it was compiled. As a workaround, you can use the counterpart methods in QueryFactory which allow the generic types to be specified explicitly.
	at com.googlecode.cqengine.query.QueryFactory.validateSimpleFunctionGenericTypes(QueryFactory.java:1084)
	at com.googlecode.cqengine.query.QueryFactory.resolveSimpleFunctionGenericTypes(QueryFactory.java:1070)
	at com.googlecode.cqengine.query.QueryFactory.attribute(QueryFactory.java:848)
	at de.adorsys.keymanagement.core.view.EntryViewImpl.<clinit>(EntryViewImpl.java:35)`

https://github.com/npgall/cqengine/blob/master/documentation/LambdaAttributes.md

**Comment by cemkayan** [comment]
I am facing a similar issue any idea on it ?

**Comment by valb3r** [comment]
Generic attributes should be explicitly specified, so this would require making a new release of the library. The easiest workaround is to change JRE to i.e. https://adoptopenjdk.net/releases.html

**Comment by cemkayan** [comment]
thanks for your message and suggestion... switched to below one, but still having the same issue 
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Temurin-11.0.12+7 (build 11.0.12+7)

**Comment by max402** [comment]
Use of CQEngine was refactored in the transition to JDK17. The issue is no more relevant

**Comment by max402** [comment]
Use of CQEngine was refactored in the transition to JDK17. The issue is no more relevant
